name: Go
on: [push]
jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.13]
    name: Go ${{ matrix.go }} | OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v .

    - name: Test
      run: go test -v -race -cover ./...
